spring:
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URI:mongodb+srv://apiprodutos:FQGQc80yZxQ341n0@ia-teste.vpt51es.mongodb.net/?retryWrites=true&w=majority&appName=post-ai-database}
      database: ia-teste
      auto-index-creation: true

processor:
  host: ${HOSTPROCESSOR:http://92.113.33.84:5000}
  limitAudio: 90

whatsapp:
  retry:
    maxAttempts: 5

server:
  port: 8181