spring:
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URI}
      database: ia-teste
      auto-index-creation: true

processor:
  host: ${HOSTPROCESSOR}
  limitAudio: 10

whatsapp:
  retry:
    maxAttempts: 5
  evolution:
    host: ${EVOLUTION_HOST}
    api-key: ${EVOLUTION_API_KEY}
  meta:
    graph-base-url: ${META_GRAPH_BASE_URL}
    graph-version: ${META_GRAPH_VERSION}

server:
  port: 8181