version: '3.8'

services:
  api-menssage-processor-api:
    container_name: api-menssage-processor-api
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8181:8181"
